version: "3"

services:
  producer:
    build: .
    command: python3 -u producer.py
    working_dir: /pyarrowdemo
    volumes:
      - .:/pyarrowdemo:ro
      - /tmp/pyarrowdemo:/tmp/pyarrowdemo

  consumer:
    build: .
    command: python3 -u consumer.py
    working_dir: /pyarrowdemo
    volumes:
      - .:/pyarrowdemo:ro
      - /tmp/pyarrowdemo:/tmp/pyarrowdemo
    depends_on:
      - producer
